services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: calidus
      POSTGRES_PASSWORD: calidus123
      POSTGRES_DB: calidus
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U calidus"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://calidus:calidus123@db:5432/calidus
      - TEST_DATABASE_URL=postgresql://calidus:calidus123@db:5432/calidus_test
      - REDIS_URL=redis://redis:6379/0
      - ANTHROPIC_API_KEY=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
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
