services:
  postgres:
    image: postgres:15-alpine
    container_name: calidus-postgres
    environment:
      POSTGRES_USER: calidus
      POSTGRES_PASSWORD: calidus_dev_2024
      POSTGRES_DB: calidus_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U calidus"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: calidus-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: calidus-backend
    environment:
      DATABASE_URL: postgresql://calidus:calidus_dev_2024@postgres:5432/calidus_db
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY: calidus_dev_secret_key_2024_change_in_production
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./synthetic_requirements:/app/synthetic_requirements
      - ./rawdata:/app/rawdata
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
  redis_data:
