"""add_impact_analysis_tables

Revision ID: 23a663f00df1
Revises: 5672782aaa41
Create Date: 2025-10-21 17:23:28.394894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23a663f00df1'
down_revision: Union[str, None] = '5672782aaa41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('impact_analysis_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('analyzed_by_id', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risklevel'), nullable=False),
    sa.Column('upstream_count', sa.Integer(), nullable=True),
    sa.Column('downstream_count', sa.Integer(), nullable=True),
    sa.Column('test_case_count', sa.Integer(), nullable=True),
    sa.Column('regulatory_impact', sa.Boolean(), nullable=True),
    sa.Column('upstream_tree', sa.JSON(), nullable=True),
    sa.Column('downstream_tree', sa.JSON(), nullable=True),
    sa.Column('affected_requirements', sa.JSON(), nullable=True),
    sa.Column('affected_test_cases', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('regulatory_implications', sa.JSON(), nullable=True),
    sa.Column('risk_factors', sa.JSON(), nullable=True),
    sa.Column('estimated_effort_hours', sa.Float(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analyzed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_impact_analysis_reports_id'), 'impact_analysis_reports', ['id'], unique=False)
    op.create_index(op.f('ix_impact_analysis_reports_requirement_id'), 'impact_analysis_reports', ['requirement_id'], unique=False)
    op.create_index(op.f('ix_impact_analysis_reports_risk_level'), 'impact_analysis_reports', ['risk_level'], unique=False)
    op.create_table('change_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('impact_report_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('proposed_changes', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'IMPLEMENTED', 'CANCELLED', name='changerequeststatus'), nullable=True),
    sa.Column('requested_by_id', sa.Integer(), nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('review_comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('implemented_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['impact_report_id'], ['impact_analysis_reports.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_requests_id'), 'change_requests', ['id'], unique=False)
    op.create_index(op.f('ix_change_requests_requirement_id'), 'change_requests', ['requirement_id'], unique=False)
    op.create_index(op.f('ix_change_requests_status'), 'change_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_change_requests_status'), table_name='change_requests')
    op.drop_index(op.f('ix_change_requests_requirement_id'), table_name='change_requests')
    op.drop_index(op.f('ix_change_requests_id'), table_name='change_requests')
    op.drop_table('change_requests')
    op.drop_index(op.f('ix_impact_analysis_reports_risk_level'), table_name='impact_analysis_reports')
    op.drop_index(op.f('ix_impact_analysis_reports_requirement_id'), table_name='impact_analysis_reports')
    op.drop_index(op.f('ix_impact_analysis_reports_id'), table_name='impact_analysis_reports')
    op.drop_table('impact_analysis_reports')
    # ### end Alembic commands ###
