"""Add missing test case fields: executed_by, test_type, test_environment, automated, automation_script

Revision ID: 291d240bee98
Revises: 34df7477d651
Create Date: 2025-10-19 07:32:42.730163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '291d240bee98'
down_revision: Union[str, None] = '34df7477d651'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_cases', sa.Column('executed_by', sa.String(length=100), nullable=True))
    op.add_column('test_cases', sa.Column('test_type', sa.String(length=50), nullable=True))
    op.add_column('test_cases', sa.Column('test_environment', sa.String(length=100), nullable=True))
    op.add_column('test_cases', sa.Column('automated', sa.Boolean(), nullable=True))
    op.add_column('test_cases', sa.Column('automation_script', sa.String(length=500), nullable=True))
    op.drop_column('test_cases', 'environment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_cases', sa.Column('environment', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('test_cases', 'automation_script')
    op.drop_column('test_cases', 'automated')
    op.drop_column('test_cases', 'test_environment')
    op.drop_column('test_cases', 'test_type')
    op.drop_column('test_cases', 'executed_by')
    # ### end Alembic commands ###
